/**
 * Design tokens copied verbatim from qassan-phase2/design-reference-app.jsx,
 * which Med approved. Values are not adjusted "to taste": the reference is the
 * agreed design, and drifting from it by a few hex digits is how an approved
 * look quietly becomes a different one.
 */
// CSS-variable references, not literals. globals.css defines the values for
// dark (:root) and light (:root[data-theme=light]), so every `style={{ color:
// T.text }}` becomes theme-aware without touching a single component. The map's
// vivid data colours are intentionally NOT here — they stay hardcoded so a cut
// looks the same red in both themes.
export const T = {
  night: "var(--bg)",
  surface: "var(--surface)",
  surface2: "var(--surface2)",
  line: "var(--border)",
  amber: "var(--amber)", // electricity
  amberDim: "var(--amber-dim)", // a cut window already in the past
  aqua: "var(--aqua)", // water
  live: "var(--live)", // happening right now
  observed: "var(--observed)", // social observation — unconfirmed, not official
  text: "var(--text)",
  muted: "var(--muted)",
  ok: "var(--ok)",
} as const;

export type Lang = "ar" | "fr";

/** Arabic first, French second — the reference's order, and Tunisia's. */
export const STR = {
  ar: {
    appName: "قصّان",
    tagline: "الضو والماء في تونس — لحظة بلحظة",
    myArea: "منطقتي",
    pickArea: "اختر منطقتك",
    govLabel: "الولاية",
    cityLabel: "المدينة / المعتمدية",
    hoodLabel: "الحي",
    optional: "اختياري",
    cityNamed: "منطقتك مذكورة بالاسم في البلاغ",
    govOnly: "ولايتك معنيّة — منطقتك بالتحديد غير مؤكدة",
    liveNow: "جاري الآن",
    cutNow: "مقصوص توّا",
    poweredNow: "الضو موجود",
    nextCut: "أقرب قطع محتمل",
    noArea: "منطقتك ما ظهرتش في البلاغات — نراقبو ونعلموك",
    today: "اليوم",
    all: "الكل",
    elec: "الضو",
    water: "الماء",
    planned: "مبرمج",
    sudden: "عطب فجئي",
    endsUnknown: "بدون توقيت رجوع رسمي",
    source: "المصدر",
    timeline: "خط النهار — منطقتك",
    areas: "المناطق المذكورة",
    reports: "بلاغات السكان",
    reportCut: "مقصوص توّا",
    reportBack: "رجع",
    reportWhich: "شنوّا تبلّغ عليه؟",
    pickAreaFirst: "اختر منطقتك أولا",
    confirmedElec: "أكّدو قطع الضو",
    confirmedWater: "أكّدو قطع الماء",
    confirmed: "أكّدو",
    beFirst: "كن أول من يأكد",
    whyTitle: "علاش يقصّو الضو؟",
    whyBody:
      "وقت الذروة الطلب على الكهرباء يتجاوز قدرة الإنتاج، فيقع قطع دوري بالتداول باش ما تنهارش الشبكة الكل.",
    hotline: "رقم الستاغ للطوارئ: 71.239.222",
    sources: "المصادر: بلاغات الستاغ والصوناد + الصحافة التونسية",
    beta: "نسخة تجريبية",
    useMyLocation: "حدّد موقعي",
    locating: "جاري التحديد…",
    locationDenied: "ما نجّمناش نحدّدو موقعك — اختر منطقتك يدويا",
    ended: "انتهى",
    upcoming: "قادم",
    observed: "رصد من مواقع التواصل — غير مؤكد",
    observedShort: "غير مؤكد",
    mapUpcoming: "قطع متوقع اليوم",
    tapGov: "👆 اضغط على ولاية لعرض معتمدياتها",
    namedInBulletin: "المناطق المذكورة في البلاغ",
    tabHome: "اليوم", tabMap: "الخريطة", tabReport: "بلّغ", tabAreas: "المناطق", tabStats: "إحصائيات",
    reportStep1: "١ · نوع الخدمة", reportStep2: "٢ · الحالة", reportStep3: "٣ · المنطقة",
    reportSubmit: "أرسل التبليغ", reportThanks: "شكرا، وصل بلاغك — يعاون جيرانك",
    searchArea: "ابحث عن منطقتك…", statusOut: "مقصوص", statusOn: "يخدم", statusNoData: "لا توجد بيانات",
    lastReport: "آخر تبليغ", noAreas: "ما لقيناش نتيجة",
    statActive: "انقطاعات جارية", statUpcoming: "قطع متوقّع اليوم", statReports24: "تبليغات (٢٤ ساعة)",
    statApproved: "بلاغات مصادق عليها", statSoon: "الإحصائيات المتقدّمة قريبا",
    statSoonBody: "التوقّعات والاتجاهات تظهر فقط لمّا يكون عندنا معطيات كافية — بعيّنة معلومة، بدون تخمين.",
    themeToggle: "الوضع",
  },
  fr: {
    appName: "9assan",
    tagline: "Électricité & eau en Tunisie — en temps réel",
    myArea: "Ma zone",
    pickArea: "Choisir ma zone",
    govLabel: "Gouvernorat",
    cityLabel: "Ville / délégation",
    hoodLabel: "Quartier",
    optional: "optionnel",
    cityNamed: "Votre zone est citée nommément dans le communiqué",
    govOnly: "Gouvernorat concerné — votre zone exacte non confirmée",
    liveNow: "En cours",
    cutNow: "Coupé maintenant",
    poweredNow: "Courant disponible",
    nextCut: "Prochaine coupure probable",
    noArea: "Votre zone n'apparaît pas — on surveille pour vous",
    today: "Aujourd'hui",
    all: "Tout",
    elec: "Électricité",
    water: "Eau",
    planned: "Programmée",
    sudden: "Panne soudaine",
    endsUnknown: "Retour sans préavis officiel",
    source: "Source",
    timeline: "Votre journée",
    areas: "Zones citées",
    reports: "Signalements citoyens",
    reportCut: "Coupé maintenant",
    reportBack: "Rétabli",
    reportWhich: "Signaler quoi ?",
    pickAreaFirst: "Choisissez d'abord votre zone",
    confirmedElec: "coupure élec. confirmée par",
    confirmedWater: "coupure eau confirmée par",
    confirmed: "confirmé par",
    beFirst: "Soyez le premier à confirmer",
    whyTitle: "Pourquoi ces coupures ?",
    whyBody:
      "Au pic, la demande dépasse la capacité de production — d'où le délestage tournant pour éviter l'effondrement du réseau.",
    hotline: "Urgences STEG : 71.239.222",
    sources: "Sources : communiqués STEG & SONEDE + presse tunisienne",
    beta: "Bêta",
    useMyLocation: "Me localiser",
    locating: "Localisation…",
    locationDenied: "Localisation impossible — choisissez votre zone",
    ended: "Terminé",
    upcoming: "À venir",
    observed: "Observation réseaux sociaux — non confirmé",
    observedShort: "Non confirmé",
    mapUpcoming: "Coupure prévue aujourd'hui",
    tapGov: "👆 Touchez un gouvernorat pour ses délégations",
    namedInBulletin: "Zones citées dans le communiqué",
    tabHome: "Aujourd'hui", tabMap: "Carte", tabReport: "Signaler", tabAreas: "Villes", tabStats: "Stats",
    reportStep1: "1 · Service", reportStep2: "2 · État", reportStep3: "3 · Zone",
    reportSubmit: "Envoyer", reportThanks: "Merci, signalement reçu",
    searchArea: "Cherchez votre zone…", statusOut: "Coupé", statusOn: "OK", statusNoData: "Aucune donnée",
    lastReport: "Dernier signalement", noAreas: "Aucun résultat",
    statActive: "Coupures en cours", statUpcoming: "Prévues aujourd'hui", statReports24: "Signalements (24 h)",
    statApproved: "Communiqués validés", statSoon: "Statistiques avancées bientôt",
    statSoonBody: "Prévisions et tendances n'apparaîtront qu'avec des données suffisantes — échantillon connu, sans conjecture.",
    themeToggle: "Thème",
  },
} as const;
