-- Backfill French delegation names from HDX COD-AB (INS, official).
-- Only fills name_fr where it is currently NULL; never overwrites.
-- 173 rows. Matched by Arabic name within governorate.

UPDATE places SET name_fr = 'Bab Bhar' WHERE id = 400 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Omrane' WHERE id = 323 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Omrane Supérieur' WHERE id = 320 AND name_fr IS NULL;
UPDATE places SET name_fr = 'El Menzah' WHERE id = 499 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Cité El Khadra' WHERE id = 491 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Kabaria' WHERE id = 378 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Sidi El Béchir' WHERE id = 359 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Jebel Jelloud' WHERE id = 470 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Ettadhamen' WHERE id = 318 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Nouvelle Médina' WHERE id = 410 AND name_fr IS NULL;
UPDATE places SET name_fr = 'El Mourouj' WHERE id = 429 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Hammam Chott' WHERE id = 417 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Boumhel' WHERE id = 394 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Borj El Amri' WHERE id = 452 AND name_fr IS NULL;
UPDATE places SET name_fr = 'El Battan' WHERE id = 489 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Dar Chaabane El Fehri' WHERE id = 476 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Beni Khiar' WHERE id = 393 AND name_fr IS NULL;
UPDATE places SET name_fr = 'El Mida' WHERE id = 501 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Hammam Ghezaz' WHERE id = 360 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Haouaria' WHERE id = 474 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Takelsa' WHERE id = 479 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Menzel Bouzelfa' WHERE id = 370 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Grombalia' WHERE id = 456 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Bou Argoub' WHERE id = 322 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Zriba' WHERE id = 314 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Bir Mchergua' WHERE id = 463 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Nadhour' WHERE id = 309 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Saouaf' WHERE id = 459 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Jarzouna' WHERE id = 331 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Sejnane' WHERE id = 488 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Joumine' WHERE id = 354 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Ghazala' WHERE id = 375 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Tinja' WHERE id = 435 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Utique' WHERE id = 421 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Menzel Jemil' WHERE id = 317 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Béja Sud' WHERE id = 395 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Amdoun' WHERE id = 461 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Thibar' WHERE id = 498 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Goubellat' WHERE id = 384 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Jendouba Nord' WHERE id = 351 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Aïn Draham' WHERE id = 373 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Oued Mliz' WHERE id = 424 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Balta Bou Aouane' WHERE id = 350 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Kef Ouest' WHERE id = 349 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Kef Est' WHERE id = 418 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Nebeur' WHERE id = 340 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Sakiet Sidi Youssef' WHERE id = 372 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Kalaat Senan' WHERE id = 390 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Ksour' WHERE id = 425 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Es Sers' WHERE id = 361 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Siliana Nord' WHERE id = 346 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Siliana Sud' WHERE id = 494 AND name_fr IS NULL;
UPDATE places SET name_fr = 'El Krib' WHERE id = 405 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Kesra' WHERE id = 315 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Bargou' WHERE id = 409 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Laroussa' WHERE id = 447 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Sousse Riadh' WHERE id = 453 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Sousse Jaouhara' WHERE id = 467 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Sousse Sidi Abdelhamid' WHERE id = 319 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Akouda' WHERE id = 442 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Kalaa Kebira' WHERE id = 389 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Sidi Bou Ali' WHERE id = 436 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Hergla' WHERE id = 505 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Bouficha' WHERE id = 431 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Kondar' WHERE id = 471 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Sidi El Heni' WHERE id = 472 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Kalaa Sghira' WHERE id = 391 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Ouerdanine' WHERE id = 316 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Sahline' WHERE id = 339 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Zeramdine' WHERE id = 446 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Beni Hassen' WHERE id = 411 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Jammel' WHERE id = 404 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Bembla' WHERE id = 457 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Moknine' WHERE id = 500 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Bekalta' WHERE id = 458 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Teboulba' WHERE id = 460 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Ksar Hellal' WHERE id = 343 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Ksibet El Mediouni' WHERE id = 337 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Boumerdès' WHERE id = 362 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Chorbane' WHERE id = 330 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Hbira' WHERE id = 439 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Souassi' WHERE id = 381 AND name_fr IS NULL;
UPDATE places SET name_fr = 'El Jem' WHERE id = 503 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Chebba' WHERE id = 451 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Melloulech' WHERE id = 415 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Sidi Alouane' WHERE id = 398 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Ksour Essef' WHERE id = 484 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Sakiet Eddaier' WHERE id = 355 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Sfax Sud' WHERE id = 399 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Thyna' WHERE id = 324 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Agareb' WHERE id = 379 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Jebeniana' WHERE id = 356 AND name_fr IS NULL;
UPDATE places SET name_fr = 'El Amra' WHERE id = 465 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Hencha' WHERE id = 377 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Menzel Chaker' WHERE id = 482 AND name_fr IS NULL;
UPDATE places SET name_fr = 'El Ghraiba' WHERE id = 333 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Bir Ali Ben Khélifa' WHERE id = 448 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Skhira' WHERE id = 464 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Mahres' WHERE id = 383 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Kerkennah' WHERE id = 497 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Kairouan Nord' WHERE id = 325 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Kairouan Sud' WHERE id = 364 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Chebika' WHERE id = 412 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Sbikha' WHERE id = 449 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Oueslatia' WHERE id = 313 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Haffouz' WHERE id = 433 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Alaa' WHERE id = 308 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Hajeb El Ayoun' WHERE id = 341 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Nasrallah' WHERE id = 327 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Chrarda' WHERE id = 480 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Bouhajla' WHERE id = 483 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Kasserine Nord' WHERE id = 477 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Kasserine Sud' WHERE id = 475 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Ezzouhour' WHERE id = 387 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Hassi El Ferid' WHERE id = 440 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Sbeitla' WHERE id = 426 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Sbiba' WHERE id = 392 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Jedeliane' WHERE id = 496 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Ayoun' WHERE id = 334 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Thala' WHERE id = 416 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Hidra' WHERE id = 462 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Foussana' WHERE id = 441 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Feriana' WHERE id = 454 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Majel Belabbes' WHERE id = 321 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Sidi Bouzid Ouest' WHERE id = 406 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Sidi Bouzid Est' WHERE id = 363 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Jelma' WHERE id = 358 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Bir El Hfay' WHERE id = 427 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Sidi Ali Ben Aoun' WHERE id = 369 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Menzel Bouzaiene' WHERE id = 348 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Meknassi' WHERE id = 407 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Mazzouna' WHERE id = 326 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Regueb' WHERE id = 380 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Ouled Haffouz' WHERE id = 450 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Gabès Ouest' WHERE id = 413 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Gabès Sud' WHERE id = 486 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Ghannouch' WHERE id = 366 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Metouia' WHERE id = 368 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Menzel Habib' WHERE id = 385 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Matmata' WHERE id = 357 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Matmata Nouvelle' WHERE id = 347 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Mareth' WHERE id = 445 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Médenine Nord' WHERE id = 430 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Médenine Sud' WHERE id = 353 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Beni Khedache' WHERE id = 338 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Ben Guerdane' WHERE id = 506 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Djerba Midoun' WHERE id = 386 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Sidi Makhlouf' WHERE id = 342 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Tataouine Nord' WHERE id = 423 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Tataouine Sud' WHERE id = 428 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Samar' WHERE id = 490 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Bir Lahmar' WHERE id = 443 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Ghomrassen' WHERE id = 420 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Remada' WHERE id = 311 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Gafsa Nord' WHERE id = 432 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Sidi Aich' WHERE id = 374 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Ksar' WHERE id = 401 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Gafsa Sud' WHERE id = 328 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Oum Larais' WHERE id = 352 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Redeyef' WHERE id = 481 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Metlaoui' WHERE id = 332 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Guetar' WHERE id = 422 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Belkhir' WHERE id = 367 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Sened' WHERE id = 371 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Degueche' WHERE id = 473 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Tamaghza' WHERE id = 382 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Nefta' WHERE id = 495 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Hazoua' WHERE id = 397 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Kebili Sud' WHERE id = 402 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Kebili Nord' WHERE id = 365 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Souk El Ahed' WHERE id = 396 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Douz Nord' WHERE id = 307 AND name_fr IS NULL;
UPDATE places SET name_fr = 'Douz Sud' WHERE id = 312 AND name_fr IS NULL;

SELECT count(*) FILTER (WHERE name_fr IS NOT NULL) AS with_fr, count(*) AS total
FROM places WHERE level = 'delegation';