-- ============================================================
-- QASSAN — Seed v1: place registry + parser audit column
-- Run AFTER qassan-schema.sql, in the Supabase SQL editor.
-- ============================================================

-- Audit trail: keep the parser's full JSON output per document
ALTER TABLE raw_documents ADD COLUMN IF NOT EXISTS parsed_json JSONB;

-- ---------- Governorates (24) ----------
INSERT INTO places (level, name_ar, name_fr, aliases) VALUES
('governorate','تونس','Tunis','["تونس الكبرى","Grand Tunis","tunis"]'),
('governorate','أريانة','Ariana','["اريانة","Ariana","L''Ariana"]'),
('governorate','بن عروس','Ben Arous','["بن عروس","Ben Arous"]'),
('governorate','منوبة','Manouba','["منّوبة","La Manouba","Mannouba"]'),
('governorate','نابل','Nabeul','["نابل","Nabeul","الوطن القبلي","Cap Bon"]'),
('governorate','زغوان','Zaghouan','["زغوان","Zaghouan"]'),
('governorate','بنزرت','Bizerte','["بنزرت","Bizerte"]'),
('governorate','باجة','Béja','["باجة","Beja","Béja"]'),
('governorate','جندوبة','Jendouba','["جندوبة","Jendouba"]'),
('governorate','الكاف','Le Kef','["الكاف","Kef","Le Kef"]'),
('governorate','سليانة','Siliana','["سليانة","Siliana"]'),
('governorate','القيروان','Kairouan','["القيروان","Kairouan"]'),
('governorate','القصرين','Kasserine','["القصرين","Kasserine"]'),
('governorate','سيدي بوزيد','Sidi Bouzid','["سيدي بوزيد","Sidi Bouzid"]'),
('governorate','سوسة','Sousse','["سوسة","Sousse"]'),
('governorate','المنستير','Monastir','["المنستير","Monastir"]'),
('governorate','المهدية','Mahdia','["المهدية","Mahdia"]'),
('governorate','صفاقس','Sfax','["صفاقس","Sfax"]'),
('governorate','قفصة','Gafsa','["قفصة","Gafsa"]'),
('governorate','توزر','Tozeur','["توزر","Tozeur"]'),
('governorate','قبلي','Kébili','["قبلي","Kebili","Kébili"]'),
('governorate','قابس','Gabès','["قابس","Gabes","Gabès"]'),
('governorate','مدنين','Médenine','["مدنين","Medenine","Médenine"]'),
('governorate','تطاوين','Tataouine','["تطاوين","Tataouine"]');

-- ---------- Known localities (from July 2026 announcements; grows automatically) ----------
-- parent = governorate; alias lists grow every time the parser meets a new spelling
WITH gov AS (SELECT id, name_ar FROM places WHERE level='governorate')
INSERT INTO places (level, parent_id, name_ar, name_fr, aliases)
SELECT 'delegation', gov.id, v.name_ar, v.name_fr, v.aliases::jsonb
FROM (VALUES
 ('تونس','المنازه','El Menzah','["المنزه","El Menzah","المنازه"]'),
 ('تونس','عين زغوان','Aïn Zaghouan','["عين زغوان","Ain Zaghouan"]'),
 ('تونس','حدائق قرطاج','Jardins de Carthage','["حدائق قرطاج","Jardins de Carthage"]'),
 ('تونس','قصر السعيد','Ksar Saïd','["قصر السعيد","Ksar Said"]'),
 ('تونس','الكرم','Le Kram','["الكرم","Kram","Le Kram"]'),
 ('تونس','حلق الوادي','La Goulette','["حلق الوادي","La Goulette"]'),
 ('تونس','قرطاج','Carthage','["قرطاج","Carthage"]'),
 ('تونس','المرسى','La Marsa','["المرسى","La Marsa"]'),
 ('تونس','باردو','Le Bardo','["باردو","Bardo","Le Bardo"]'),
 ('تونس','الحرايرية','El Hrairia','["الحرايرية","Hrairia","El Hrairia"]'),
 ('تونس','الزهور','Ezzouhour','["الزهور","Ezzouhour"]'),
 ('تونس','سيدي حسين','Sidi Hassine','["سيدي حسين","Sidi Hassine"]'),
 ('تونس','الوردية','El Ouardia','["الوردية","Ouardia"]'),
 ('تونس','السيجومي','Séjoumi','["السيجومي","Sejoumi"]'),
 ('أريانة','أريانة المدينة','Ariana Ville','["أريانة المدينة","Ariana Ville"]'),
 ('أريانة','سكرة','La Soukra','["سكرة","Soukra","La Soukra"]'),
 ('أريانة','رواد','Raoued','["رواد","Raoued"]'),
 ('أريانة','المنيهلة','Mnihla','["المنيهلة","Mnihla"]'),
 ('أريانة','التضامن','Ettadhamen','["التضامن","Ettadhamen"]'),
 ('أريانة','قلعة الأندلس','Kalâat el-Andalous','["قلعة الأندلس","Kalaat el Andalous"]'),
 ('أريانة','سيدي ثابت','Sidi Thabet','["سيدي ثابت","Sidi Thabet"]'),
 ('أريانة','برج الطويل','Borj Touil','["برج الطويل","Borj Touil","برج الطويل"]'),
 ('بن عروس','بن عروس','Ben Arous','["بن عروس"]'),
 ('بن عروس','المحمدية','Mohamedia','["المحمدية","Mohamedia"]'),
 ('بن عروس','فوشانة','Fouchana','["فوشانة","Fouchana"]'),
 ('بن عروس','برج السدرية','Borj Cédria','["برج السدرية","Borj Cedria"]'),
 ('بن عروس','حمام الأنف','Hammam Lif','["حمام الأنف","Hammam Lif"]'),
 ('بن عروس','رادس','Radès','["رادس","Rades"]'),
 ('بن عروس','مقرين','Mégrine','["مقرين","Megrine"]'),
 ('بن عروس','الزهراء','Ezzahra','["الزهراء","Ezzahra"]'),
 ('بن عروس','مرناق','Mornag','["مرناق","Mornag"]'),
 ('منوبة','منوبة','Manouba','["منوبة"]'),
 ('منوبة','الجديدة','El Jedaida','["الجديدة","Jedaida","El Jedaida"]'),
 ('منوبة','دوار هيشر','Douar Hicher','["دوار هيشر","Douar Hicher"]'),
 ('منوبة','وادي الليل','Oued Ellil','["وادي الليل","Oued Ellil"]'),
 ('منوبة','طبربة','Tebourba','["طبربة","Tebourba"]'),
 ('منوبة','المرناقية','Mornaguia','["المرناقية","Mornaguia"]'),
 ('نابل','نابل','Nabeul','["نابل"]'),
 ('نابل','الحمامات','Hammamet','["الحمامات","Hammamet"]'),
 ('نابل','منزل تميم','Menzel Temime','["منزل تميم","Menzel Temime","منزل تميم الشمالية"]'),
 ('نابل','قربة','Korba','["قربة","Korba"]'),
 ('نابل','تازركة','Tazarka','["تازركة","Tazarka"]'),
 ('نابل','قليبية','Kélibia','["قليبية","Kelibia"]'),
 ('نابل','سليمان','Soliman','["سليمان","Soliman"]'),
 ('نابل','بني خلاد','Béni Khalled','["بني خلاد","Beni Khalled"]'),
 ('نابل','الصمعة','Somâa','["الصمعة","Somaa"]'),
 ('نابل','الحمامة','El Hammema','["الحمامة"]'),
 ('نابل','المرازقة','Mrazga','["المرازقة","Mrazga"]'),
 ('بنزرت','بنزرت المدينة','Bizerte Ville','["بنزرت المدينة"]'),
 ('بنزرت','منزل بورقيبة','Menzel Bourguiba','["منزل بورقيبة","Menzel Bourguiba"]'),
 ('بنزرت','ماطر','Mateur','["ماطر","Mateur"]'),
 ('بنزرت','رأس الجبل','Ras Jebel','["رأس الجبل","Ras Jebel"]'),
 ('بنزرت','العالية','El Alia','["العالية","El Alia"]'),
 ('زغوان','زغوان','Zaghouan','["زغوان"]'),
 ('زغوان','الفحص','El Fahs','["الفحص","El Fahs"]'),
 ('سوسة','سوسة المدينة','Sousse Ville','["سوسة المدينة"]'),
 ('سوسة','النفيضة','Enfidha','["النفيضة","Enfidha"]'),
 ('سوسة','حمام سوسة','Hammam Sousse','["حمام سوسة","Hammam Sousse"]'),
 ('سوسة','مساكن','M''saken','["مساكن","Msaken"]'),
 ('صفاقس','صفاقس المدينة','Sfax Ville','["صفاقس المدينة"]'),
 ('صفاقس','ساقية الزيت','Sakiet Ezzit','["ساقية الزيت","Sakiet Ezzit"]'),
 ('صفاقس','ساقية الداير','Sakiet Eddaïer','["ساقية الداير","Sakiet Eddaier"]'),
 ('قابس','قابس المدينة','Gabès Ville','["قابس المدينة"]'),
 ('قابس','الحامة','El Hamma','["الحامة","El Hamma"]'),
 ('مدنين','جربة حومة السوق','Djerba Houmt Souk','["جربة","Djerba","حومة السوق"]'),
 ('مدنين','جرجيس','Zarzis','["جرجيس","Zarzis"]'),
 ('جندوبة','جندوبة','Jendouba','["جندوبة"]'),
 ('جندوبة','بوسالم','Bou Salem','["بوسالم","Bou Salem"]'),
 ('جندوبة','غار الدماء','Ghardimaou','["غار الدماء","Ghardimaou"]'),
 ('جندوبة','طبرقة','Tabarka','["طبرقة","Tabarka"]'),
 ('جندوبة','فرنانة','Fernana','["فرنانة","Fernana"]'),
 ('جندوبة','وشتاتة','Ouechtata','["وشتاتة","Ouechtata"]'),
 ('باجة','باجة الشمالية','Béja Nord','["باجة الشمالية"]'),
 ('باجة','مجاز الباب','Medjez el-Bab','["مجاز الباب","Medjez el Bab"]'),
 ('باجة','تستور','Testour','["تستور","Testour"]'),
 ('باجة','نفزة','Nefza','["نفزة","Nefza"]'),
 ('باجة','تبرسق','Téboursouk','["تبرسق","Teboursouk"]'),
 ('الكاف','الدهماني','Dahmani','["الدهماني","Dahmani"]'),
 ('الكاف','الجريصة','Jérissa','["الجريصة","Jerissa"]'),
 ('الكاف','نبّر','Nebeur','["نبر","نبّر","Nebeur"]'),
 ('الكاف','تاجروين','Tajerouine','["تاجروين","Tajerouine"]'),
 ('سليانة','سليانة','Siliana','["سليانة"]'),
 ('سليانة','بوعرادة','Bou Arada','["بوعرادة","Bou Arada"]'),
 ('سليانة','مكثر','Makthar','["مكثر","Makthar"]'),
 ('سليانة','الروحية','Rouhia','["الروحية","Rouhia"]'),
 ('سليانة','قعفور','Gaâfour','["قعفور","Gaafour"]')
) AS v(gov_ar, name_ar, name_fr, aliases)
JOIN gov ON gov.name_ar = v.gov_ar;
